#ifndef	__ARM_SYSTICK_DEFS_H__
#define	__ARM_SYSTICK_DEFS_H__

#include <os/bit.h>

#define	ARM_SYSTICK_BASE		0xe000e010

#define	ARM_SYSTICK_REG_STK_CTRL			0x000
#define		ARM_SYSTICK_REG_STK_CTRL_ENABLE		BIT_U32(0)
#define		ARM_SYSTICK_REG_STK_CTRL_TICKINT	BIT_U32(1)
#define		ARM_SYSTICK_REG_STK_CTRL_CLKSOURCE	BIT_U32(2)
#define		ARM_SYSTICK_REG_STK_CTRL_COUNTFLAG	BIT_U32(16)

#define	ARM_SYSTICK_REG_STK_LOAD			0x004
#define		ARM_SYSTICK_REG_STK_LOAD_RELOAD_M	0x00ffffff
#define		ARM_SYSTICK_REG_STK_LOAD_RELOAD_S	0

#define	ARM_SYSTICK_REG_STK_VAL				0x008
#define		ARM_SYSTICK_REG_STK_VAL_CURRENT_M	0x00ffffff
#define		ARM_SYSTICK_REG_STK_VAL_CURRENT_S	0

#define	ARM_SYSTICK_REG_STK_CALIB			0x00c
#define		ARM_SYSTICK_REG_STK_CALIB_TENMS_M	0x00ffffff
#define		ARM_SYSTICK_REG_STK_CALIB_TENMS_S	24
#define		ARM_SYSTICK_REG_STK_SKEW		BIT_U32(30)
#define		ARM_SYSTICK_REG_STK_NOREF		BIT_U32(31)

#endif	/* __ARM_SYSTICK_DEFS_H__ */
